# IBM Guestbook image version ibmcom/guestbook:v1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ibmcom/guestbook
  tag: v1
  pullPolicy: Always

replicaNum:
  desired: 2
  enabled: true

# For minikube you may want to set serviceType from LoadBalancer to NodePort
serviceType: LoadBalancer
