apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "guestbook.fullname" . }}
  labels:
    app: {{ template "guestbook.name" . }}
    release: {{ .Release.Name }}
spec:
{{ if .Values.replicaNum.enabled }}
  replicas: {{ .Values.replicaNum.desired }}
{{ else }}
  replicas: 3
{{ end }}
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http-server
          containerPort: 3000
        imagePullPolicy: {{ .Values.pullPolicy }}
